apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-secret
  namespace: garden
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: minio-secret
    creationPolicy: Owner
  data:
    - secretKey: root-user
      remoteRef:
        key: minio
        property: root-user
    - secretKey: root-password
      remoteRef:
        key: minio
        property: root-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-secret
  namespace: garden
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: postgres-secret
    creationPolicy: Owner
  data:
    - secretKey: postgres-password
      remoteRef:
        key: garden-postgres
        property: postgres-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gcp-sa-secret
  namespace: garden
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: onepassword
    kind: ClusterSecretStore
  target:
    name: gcp-sa-secret
    creationPolicy: Owner
  data:
    - secretKey: sa-key.json
      remoteRef:
        key: garden-gcp-sa
        property: sa-key
