apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: garden
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  volumeName: minio-nfs
  resources:
    requests:
      storage: 500Gi
